DROP TABLE FOOD;
DROP SEQUENCE FOOD_SEQ;

CREATE TABLE FOOD
(
    FOOD_NO         NUMBER           NOT NULL, 
    FOOD_NAME       VARCHAR2(200)    NOT NULL, 
    FOOD_GRAM       VARCHAR2(200),
    FOOD_CAR        VARCHAR2(200), 
    FOOD_PRO        VARCHAR2(200), 
    FOOD_FAT        VARCHAR2(200), 
    FOOD_CALORIE    VARCHAR2(200)	NOT NULL, 
    CONSTRAINT FOOD_PK PRIMARY KEY (FOOD_NO)
)

CREATE SEQUENCE FOOD_SEQ START WITH 9096;

SELECT * FROM FOOD;

INSERT INTO FOOD VALUES (
	004,
	'마라탕',
	'120',
	'80',
	'100',
	'100',
	'460'
)


SELECT FOOD_NAME
FROM MENTEE_DAY_MENU JOIN FOOD USING (FOOD_NO)
WHERE MENU_DATE IN '20200101';
