-- 로그인/프로필 JOIN

--로그인(join)
SELECT 
JOIN_NO, ID, JOIN_PW, JOIN_EMAIL, JOIN_ROLE, JOIN_DATE, JOIN_JOINED, JOIN_REGISTER_YN 
FROM MEMBER_JOIN;

--프로필
SELECT 
MEMBER_NO, ID, MEMBER_ROLE, 
MEMBER_REGISTER_YN, MEMBER_NAME, MEMBER_BIRTH, MEMBER_HEIGHT, MEMBER_WEIGHT
MEMBER_ADDR, MEMBER_PHONE, MEMBER_ONE_INTRO, 
MEMBER_COIN, MEMBER_CAREER, MEMBER_CONTENT, MEMBER_SCORE, --멘토
MEMBER_GENDER, MEMBER_ACTIVITY, MEMBER_BASAL, MEMBER_BMI  --멘티
FROM MEMBER_PROFILE

SELECT *
FROM MEMBER_JOIN JOIN MEMBER_PROFILE USING(ID);


-- 전체(중복제거) 출력
SELECT 
JOIN_NO, JOIN_ROLE, ID, JOIN_PW, JOIN_EMAIL, JOIN_DATE, JOIN_JOINED, JOIN_REGISTER_YN,
MEMBER_NAME, MEMBER_BIRTH, MEMBER_HEIGHT, MEMBER_WEIGHT,
MEMBER_ADDR, MEMBER_PHONE, MEMBER_ONE_INTRO, 
MEMBER_COIN, MEMBER_CAREER, MEMBER_CONTENT, MEMBER_SCORE, --멘토
MEMBER_GENDER, MEMBER_ACTIVITY, MEMBER_BASAL, MEMBER_BMI  --멘티
FROM MEMBER_JOIN JOIN MEMBER_PROFILE USING(ID);


-- 멘티 전체 출력
SELECT
JOIN_NO, JOIN_ROLE, ID, JOIN_PW, JOIN_EMAIL, JOIN_DATE, JOIN_JOINED, JOIN_REGISTER_YN,
MEMBER_NAME, MEMBER_BIRTH, MEMBER_HEIGHT, MEMBER_WEIGHT,
MEMBER_ADDR, MEMBER_PHONE, MEMBER_ONE_INTRO, 
MEMBER_COIN, MEMBER_CAREER, MEMBER_CONTENT, MEMBER_SCORE --멘토
FROM MEMBER_JOIN JOIN MEMBER_PROFILE USING(ID)
WHERE JOIN_ROLE = '멘토';


-- 멘토 전체 출력
SELECT
JOIN_NO, JOIN_ROLE, ID, JOIN_PW, JOIN_EMAIL, JOIN_DATE, JOIN_JOINED, JOIN_REGISTER_YN,
MEMBER_NAME, MEMBER_BIRTH, MEMBER_HEIGHT, MEMBER_WEIGHT,
MEMBER_ADDR, MEMBER_PHONE, MEMBER_ONE_INTRO, 
MEMBER_GENDER, MEMBER_ACTIVITY, MEMBER_BASAL, MEMBER_BMI  --멘티
FROM MEMBER_JOIN JOIN MEMBER_PROFILE USING(ID)
WHERE JOIN_ROLE = '멘티';



--아이디로 멘토 하나 출력
SELECT
JOIN_NO, JOIN_ROLE, ID, JOIN_PW, JOIN_EMAIL, JOIN_DATE, JOIN_JOINED, JOIN_REGISTER_YN,
MEMBER_NAME, MEMBER_BIRTH, MEMBER_HEIGHT, MEMBER_WEIGHT,
MEMBER_ADDR, MEMBER_PHONE, MEMBER_ONE_INTRO, 
MEMBER_COIN, MEMBER_CAREER, MEMBER_CONTENT, MEMBER_SCORE --멘토
FROM MEMBER_JOIN JOIN MEMBER_PROFILE USING(ID)
WHERE ID = 'id1234';



--아이디로 멘티 하나 출력
SELECT
JOIN_NO, JOIN_ROLE, ID, JOIN_PW, JOIN_EMAIL, JOIN_DATE, JOIN_JOINED, JOIN_REGISTER_YN,
MEMBER_NAME, MEMBER_BIRTH, MEMBER_HEIGHT, MEMBER_WEIGHT,
MEMBER_ADDR, MEMBER_PHONE, MEMBER_ONE_INTRO, 
MEMBER_GENDER, MEMBER_ACTIVITY, MEMBER_BASAL, MEMBER_BMI  --멘티
FROM MEMBER_JOIN JOIN MEMBER_PROFILE USING(ID)
WHERE ID = 'MENTEE';

