DROP TABLE MENTEE_EXERCISE_TOTAL;


--ID가 유니크이면 데이터 한 행 밖에 저장 안됨
CREATE TABLE MENTEE_EXERCISE_TOTAL(
   TOTAL_DATE         VARCHAR2(200)   NOT NULL,
   ID               VARCHAR2(200)     NOT NULL,
   TOTAL_DAYOFWEEK      VARCHAR2(200) ,
   TOTAL_TIME         VARCHAR2(200)   ,
   TOTAL_CALORY      NUMBER          ,
   TOTAL_WEIGHT      NUMBER,
   CONSTRAINT MENTEE_EXERCISE_TOTAL_PK PRIMARY KEY (TOTAL_DATE),
   CONSTRAINT MENTEE_EXERCISE_TOTAL_CH CHECK (TOTAL_DAYOFWEEK IN('일', '월', '화', '수', '목', '금', '토'))
);

SELECT TOTAL_DATE, ID, TOTAL_DAYOFWEEK, TOTAL_TIME, TOTAL_CALORY, TOTAL_WEIGHT
FROM MENTEE_EXERCISE_TOTAL;

INSERT INTO MENTEE_EXERCISE_TOTAL VALUES (
	'20200122',
	'MINTPARK',
	'목',
	60,
	240,
	55
)

SELECT *
FROM MENTEE_EXERCISE_TOTAL


SELECT TOTAL_WEIGHT
FROM MENTEE_EXERCISE_TOTAL
WHERE id IN 'MINTPARK' AND 
202001 IN (
			SELECT TO_CHAR(TOTAL_DATE, 'YYYYMM')
			FROM MENTEE_EXERCISE_TOTAL
	)
	
	
	SELECT TO_CHAR(TOTAL_DATE, 'YYYYMM')
	FROM MENTEE_EXERCISE_TOTAL
	
	
	SELECT TOTAL_DATE, ID, TOTAL_DAYOFWEEK, TOTAL_TIME, TOTAL_CALORY, TOTAL_WEIGHT
		FROM MENTEE_EXERCISE_TOTAL
		WHERE ID IN 'MINTPARK' 
		AND 202001 IN (
			SELECT TO_CHAR(TOTAL_DATE, 'YYYYMM')
			FROM MENTEE_EXERCISE_TOTAL
		)

SELECT TOTAL_DATE, ID, TOTAL_DAYOFWEEK, TOTAL_TIME, TOTAL_CALORY, TOTAL_WEIGHT
		FROM MENTEE_EXERCISE_TOTAL
		WHERE ID IN 'MINTPARK'
		AND 202001 IN (
			SELECT SUBSTR(TOTAL_DATE, 1, 6)
			FROM MENTEE_EXERCISE_TOTAL
		)
		
DELETE
FROM MENTEE_EXERCISE_TOTAL
WHERE ID = 'MENTEE01' AND TOTAL_DATE = '20200122'	


SELECT SYSDATE
FROM DUAL

SELECT TO_DATE(TOTAL_DATE, 'yyyyMMdd')
FROM MENTEE_EXERCISE_TOTAL

SELECT *
FROM MENTEE_EXERCISE_TOTAL
WHERE TO_DATE(TOTAL_DATE) BETWEEN ADD_MONTHS(SYSDATE, -1) AND SYSDATE;


--일주일전
SELECT *
FROM MENTEE_EXERCISE_TOTAL
WHERE TO_DATE(TOTAL_DATE, 'yyyyMMdd') > SYSDATE - 7;



SELECT *
FROM MENTEE_EXERCISE_TOTAL


SELECT *
FROM MENTEE_EXERCISE_TOTAL
WHERE TOTAL_DATE BETWEEN ADD_MONTHS(SYSDATE, -2) AND SYSDATE;

DELETE FROM MENTEE_EXERCISE_PLAN
			WHERE ID = 'MENTEE01'
			AND PLAN_DATE IN '20200201'
      		AND PLAN_KINDS = 'C'
      		
      		
      		 SELECT TOTAL_DATE, TOTAL_CALORIE
      FROM MENTEE_EXERCISE_TOTAL
     
      AND TOTAL_DATE BETWEEN ADD_MONTHS(SYSDATE, - 1) AND SYSDATE
      AND ID = 'MENTEE01'
      ORDER BY TOTAL_DATE ASC